### ISSUE TITLE
Running in tip mode (--from-block latest) doesn't work when connecting via http://

### ISSUE THREAD

**Issue by AlexBHarley** [celo-org/eksportisto#34]
The core issue is that tip mode over HTTP (--from-block latest causes it to run in tip mode) doesn't work, it crashes with `notifications not supported`.

#### Workarounds

-  run Eksportisto with the default nodeUri (`http://`) and make sure it auto restarts. When it gets to the tip it will crash, but then after a while it will start up again and parse recent blocks.
- always connect via WS (`--nodeUri ws://localhost:8546`). That way running Eksportisto will always just work. The only issue is that syncing the whole chain is slower over WS than HTTP

**Comment by nambrot** [comment]
Agree we should always do WS to support the main function of eksportisto

**Comment by AlexBHarley** [comment]
Closed in #35
