### ISSUE TITLE
Create inventory of alerts and dashboards that rely on eksportisto 8&11

### ISSUE THREAD

**Issue by nvtaveras** [celo-org/eksportisto#73]
Before eventually migrating the alerts (#68 and #69) and the dashboards (#70 and #71) we should make a doc listing all the current dependent alerts and dashboards along with its owners to make sure we don't miss anything during the migration, and so that their respective owners can verify nothing is broken.

**Comment by tobikuhlmann** [comment]
Inventory list: https://www.notion.so/clabsco/a81bd73cfcbf4683ad9a569e62b516f9?v=8208b0e2d821401886ef5558a7a71e95
